//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YQBYWebService.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int ID { get; set; }
        public int Users_ID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public double Price { get; set; }
        public string Distance { get; set; }
        public string Type { get; set; }
        public string Range { get; set; }
        public string Status { get; set; }
    
        public virtual user user { get; set; }
    }
}
