//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace YQBYWebService.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.ffs = new HashSet<ff>();
            this.orders = new HashSet<order>();
            this.sses = new HashSet<ss>();
        }
    
        public int ID { get; set; }
        public string Password { get; set; }
        public string Tel { get; set; }
        public string Name { get; set; }
        public string NickName { get; set; }
        public Nullable<bool> Sex { get; set; }
        public Nullable<System.DateTime> DateofBirth { get; set; }
        public Nullable<int> Marks { get; set; }
        public string Pic { get; set; }
        public Nullable<double> Wallet { get; set; }
        public string Hobby { get; set; }
    
        public virtual ICollection<ff> ffs { get; set; }
        public virtual ICollection<order> orders { get; set; }
        public virtual ICollection<ss> sses { get; set; }
    }
}
